name: "Install pip dependencies"
description: "what name says"
runs:
  using: composite
  steps:
    - name: Print step name
      run: ls
      shell: powershell
    - name: Print step name
      run: ls
      working-directory: deps
      shell: powershell
    - name: Print step name
      run: echo "Installing all required depdendencies.."
      working-directory: deps
      shell: powershell
    - name: Print step name
      run: "pip install -r requirements.txt"
      working-directory: deps
      shell: powershell
