name: "Install pip dependencies"
dascription: "what name says"
runs:
  using: composite
  steps:
    - name: Print step name
      run: |
        echo "Installing all required depdendencies.."
        "pip install -r requirements.txt"
      working-directory: deps
      shell: cmd
