name: "Deploy node app"
dascription: "Composite action to deploy node app using pm2"
inputs:
  environment:
    description: "Env where to depoloy app"
    required: true
  port:
    description: "port"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: "mtararujs/python-greetings"
        ref: "main"
        path: "deploy"
        clean: "false"
    - name: Print step name
      run: echo "Deployment to ${{inputs.environment}} has started.."
      working-directory: deploy
      shell: powershell

    # - name: Delete old process
    #   run: pm2 delete greetings-app-${{inputs.environment}} "&" set "errorlevel=0"
    #   working-directory: deploy
    #   shell: powershell

    - name: start py app process
      run: pm2 start app.py -n "greetings-app-${{inputs.environment}}" -- -- --port ${{inputs.port}}
      working-directory: deploy
      shell: powershell

    - name: Install all dependencies #delet
      run: |
        pm2 list
        pm2 list
      working-directory: deploy
      shell: powershell

    - name: Install all dependencies #delet
      run: pm2 list
      shell: powershell
